from pyparsing import *

import actions

artifact = Forward()
artifact_type = Forward()
basic_land_type = Forward()
cardtypeline = Forward()
creature = Forward()
creature_type = Forward()
enchantment = Forward()
enchantment_type = Forward()
instant = Forward()
land = Forward()
land_type = Forward()
nontype = Forward()
other_land_type = Forward()
planeswalker = Forward()
planeswalker_type  = Forward()
sorcery = Forward()
spell_type = Forward()
subtype = Forward()
subtypes = Forward()
supertype = Forward()
supertypes = Forward()
token = Forward()
tribal = Forward()
tribal_type = Forward()
type_ = Forward()
types_ = Forward()