from pyparsing import *

MAY = Forward()

BE = Forward()
HAVE = Forward()
GET = Forward()
CANT = Forward()
MUST = Forward()

DESTROY = Forward()
EXILE = Forward()
GAIN = Forward()
LOSE = Forward()
TAP = Forward()
UNTAP = Forward()
DISCARD = Forward()
SACRIFICE = Forward()
DRAW = Forward()
DEAL = Forward()
PAY = Forward()
PUT = Forward()
ATTACK = Forward()
BLOCK = Forward()
BECOME = Forward()
REDUCE = Forward()
RETURN = Forward()
ENTER = Forward()
LEAVE = Forward()
DIE = Forward()
PREVENT = Forward()
ADD = Forward()
REGENERATE = Forward()
CONTROL = Forward()
COUNTERSPELL = Forward()

EQUIP = Forward()
FORTIFY = Forward()
HAUNT = Forward()
ENCHANT = Forward()